/* 
CALENDAR TABLE + ANALYST LIST TABLE
COMPOSITE ROLE PLAYING DIMENSION FOR ANALYST METRICS
*/

--DECLARE @Calendar_Start DATE = '2017-05-01'
--DECLARE @Calendar_End DATE = '2017-06-01'
--DECLARE @Analyst VARCHAR(MAX) = 176865

SET NOCOUNT ON
IF OBJECT_ID('tempdb..#CALENDAR_TABLE') IS NOT NULL
       DROP TABLE #CALENDAR_TABLE
;


WITH CALENDAR AS (
		SELECT CAST(@Calendar_Start AS DATE) AS DATE
		UNION ALL
		SELECT DATEADD(DAY,1,DATE) FROM CALENDAR AS DATE
		WHERE DATEADD(DAY,1,DATE) <= @Calendar_End
)


SELECT DATE
	, DATENAME(WEEKDAY, [DATE])		AS [WEEKDAY NAME]
	--, DATEPART(MONTH, [DATE])		AS [MONTH]
	, DATENAME(MONTH, [DATE])		AS [MONTH NAME]
	, DATEPART(YEAR, [DATE])		AS [YEAR]


INTO #CALENDAR_TABLE
FROM CALENDAR
ORDER BY DATE
OPTION (MAXRECURSION 5000) ;


WITH ANALYSTS AS (
		SELECT DisplayName as [ANALYST], UserDimKey AS [VALUE]
		FROM UserDimvw
		WHERE UserDimKey IN (@Analyst)
)


SELECT *
FROM #CALENDAR_TABLE CROSS JOIN ANALYSTS
--ORDER BY DATE


/* 
using smart week determined in 2016
started counting week 1 as first full week - may need to change for 2017

week begins on Sunday - other week begins on monday
*/