-- PHRASE ANALYSIS
-- TESTING IDENTIFYING STRING IN A BIGGER STRING

WITH CTE AS (
	SELECT 'IN' AS TEXT, 5 AS NUM
	UNION SELECT 'IN THE', 4
	UNION SELECT 'IN THE HOUSE', 7
	UNION SELECT 'IN THE CAR', 3
	UNION SELECT 'IN MY CAR', 3
	UNION SELECT 'IN MY HOUSE', 2
	UNION SELECT 'THE CAT IN THE HOUSE', 6

)

SELECT *
	, CASE WHEN CTE.TEXT IN (SELECT T2.TEXT FROM CTE AS T2 WHERE CTE.TEXT LIKE '%' + T2.TEXT + '%' AND T2.NUM > CTE.NUM)
		THEN 'YES' END
	, CASE WHEN CTE.TEXT IN (SELECT T2.TEXT FROM CTE AS T2 WHERE T2.NUM > 5) THEN 'YES' END
	, CASE WHEN CTE.TEXT IN (SELECT T2.TEXT FROM CTE AS T2 WHERE T2.NUM > 5 AND T2.TEXT LIKE  '%'+CTE.TEXT+'%' ) THEN 'YES' END
	, CASE WHEN CTE.TEXT IN (SELECT T2.TEXT FROM CTE AS T2 WHERE T2.NUM < 5 AND T2.TEXT LIKE  '%'+CTE.TEXT+'%' ) THEN 'YES' END
	, CASE WHEN CTE.TEXT IN (SELECT T2.TEXT FROM CTE AS T2 WHERE T2.NUM <= 5 AND T2.TEXT LIKE  '%'+CTE.TEXT+'%' ) THEN 'YES' END
	, CASE WHEN CTE.TEXT IN (SELECT T2.TEXT FROM CTE AS T2 WHERE T2.NUM > CTE.NUM AND T2.TEXT LIKE  '%'+CTE.TEXT+'%' ) THEN 'YES' END
	
FROM CTE